baseurl = "/"
title = "Data Fest 2019"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-122708636-2"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    name = "Register"
    url  = "/register/"
    weight = 3

[[menu.main]]
    name = "Supporting DataFest"
    url  = "/Sponsors/"
    weight = 4

[[menu.main]]
    name = "Schedule"
    url  = "/schedule/"
    weight = 6

[[menu.main]]
    name = "FAQ"
    url  = "/faq/"
    weight = 7
    
# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:datascience@csuchico.edu"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Robin Donatello"
    defaultKeywords = ["data"]
    defaultDescription = "Data Fest at Chico State"

    # Google Maps API key (if not set will default to not passing a key.)
   # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "datascience@csuchico.edu"

    about_us = "<p>Data Fest is organized by the Data Science Initiative at Chico State. Learn more at <a href='http://datascience.csuchico.edu'>http://datascience.csuchico.edu</a></p>"
    copyright = "Copyright (c) 2018 - 2019, CSUC DSI; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p><strong>Data Science Initiative</strong>
        <br>400 West First Street
        <br>California State University, Chico
        <br>Chico
        <br>California
        <br>
        <strong>United States</strong>
      </p>
      """
    latitude = "39.7285"
    longitude = "121.8375"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files 'data/carousel'.
    # Images are kept under static/img/carousel
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files in /data/features.
    # YAML content must contain weight, name, description, (icon, url are optional)
    # if clickable, reference a folder (/feature_name/) and create /content/feature_name.md

[params.see_more]
    enable = true
    icon = "fa fa-trophy"
    #title = "Past Events at Chico"
    #subtitle = "stuff"
    link_url = "/past_events/"
    link_text = "Past Events at Chico"


[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "Hear what prior participants had to say about this event."

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Sponsors"
    subtitle = "DataFest would not be able to run without the support from the following individuals and organizations. To learn how you can contribute check the page on Supporting DataFest."



#[params.recent_posts]
#    enable = false
#    title = "Current News
#    subtitle = "You heard it here at least first."



# Other Info

# Big banner image under hugo-universal-theme/static/img/photogrid.jpg
# - Called in style.[color].css 

# Top of page Logos - can't be missing
# - logo-small.jpg shows up on small screens (110x47px, 1.9k)
# - logo.jpg shows up on desktop screens (187x42px, 2.6k) -- height more important than width. 



